AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"


Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Style/Documentation:
  Enabled: false
